![Logo_unad](https://upload.wikimedia.org/wikipedia/commons/5/5f/Logo_unad.png)

<font size=3 color="midnightblue" face="arial">
<h1 align="center">Escuela de Ciencias Básicas, Tecnología e Ingeniería</h1>
</font>

<font size=3 color="navy" face="arial">
<h1 align="center">ECBTI</h1>
</font>

<font size=2 color="darkorange" face="arial">
<h1 align="center">Curso: Métodos Numéricos</h1>
</font>

<font size=2 color="midnightblue" face="arial">
<h1 align="center">Unidad 3 - Sistemas de Ecuaciones Lineales e Interpolación Numérica</h1>
</font>

<font size=1 color="darkorange" face="arial">
<h1 align="center">Febrero 28 de 2020</h1>
</font>


***

> **Tutor:** Carlos Alberto Álvarez Henao, I.C. D.Sc.

> **skype:** carlos.alberto.alvarez.henao

> **Herramienta:** [Jupyter](http://jupyter.org/)

> **Kernel:** Python 3.7


***

## Eliminación Gaussiana Simple

A manera de ejemplo, vamos a construir un sistema de $5$ ecuaciones con $5$ incógnitas:


$$a_{11}x_1 + a_{12}x_2 + a_{13}x_3 + a_{14}x_4 + a_{15}x_5 = b_1 \hspace{1 cm} (ec. 1)$$

$$a_{21}x_1 + a_{22}x_2 + a_{23}x_3 + a_{24}x_4 + a_{25}x_5 = b_2 \hspace{1 cm} (ec. 2)$$

$$a_{31}x_1 + a_{32}x_2 + a_{33}x_3 + a_{34}x_4 + a_{35}x_5 = b_3 \hspace{1 cm} (ec. 3)$$

$$a_{41}x_1 + a_{42}x_2 + a_{43}x_3 + a_{44}x_4 + a_{45}x_5 = b_4 \hspace{1 cm} (ec. 4)$$

$$a_{51}x_1 + a_{52}x_2 + a_{53}x_3 + a_{54}x_4 + a_{55}x_5 = b_5 \hspace{1 cm} (ec. 5)$$

El método de *Eliminación Gaussiana Simple* se descompone en:


<strong>*Eliminación*:</strong> Dado el sistema 𝑨𝒙=𝒃 se realizan operaciones fundamentales de fila hasta obtener un sistema triangular superior equivalente 𝑼𝒙=𝑩

- <strong>*Etapa $1$*:</strong> Convertir todos los elementos $a_{i1}=0$ seleccionando un multiplicador de forma adecuada, en este caso $M_{i1}=a_{i1}/a_{11}$ , y calcular la nueva $i$–ésima fila como: $F_i^{(nueva)}=F_{i}−M_{i1} \times F_1$, con $2\leq i \leq n$. 


- <strong>*Etapa $2$*:</strong> Convertir todos los elementos $a_{i2}=0$ seleccionando un multiplicador de forma adecuada, en este caso $M_{i2}=a_{i2}/a_{22}$ , y calcular la nueva $i$–ésima fila como: $F_i^{(nueva)}=F_{i}−M_{i2} \times F_2$, con $3\leq i \leq n$.


- <strong>*Etapa $3$*:</strong> Convertir todos los elementos $a_{i3}=0$ seleccionando un multiplicador de forma adecuada, en este caso $M_{i3}=a_{i3}/a_{33}$ , y calcular la nueva $i$–ésima fila como: $F_i^{(nueva)}=F_{i}−M_{i3} \times F_3$, con $4\leq i \leq n$.


- $\vdots$

$$\begin{matrix} 
a_{11}x_1 &+& a_{12}x_2 &+& a_{13}x_3 &+& a_{14}x_4 &+& a_{15}x_5 &=& b_1 \\ 
          & & a_{22}^{(1)}x_2 &+& a_{23}^{(1)}x_3 &+& a_{24}^{(1)}x_4 &+& a_{25}^{(1)}x_5 &=& b_2^{(1)} \\
          & &           & & a_{33}^{(2)}x_3 &+& a_{34}^{(2)}x_4 &+& a_{35}^{(2)}x_5 &=& b_3^{(2)} \\
          & &           & &           & & a_{44}^{(3)}x_4 &+& a_{45}^{(3)}x_5 &=& b_4^{(3)} \\
          & &           & &           & &           & & a_{55}^{(4)}x_5 &=& b_5^{(4)} \\
  \end{matrix}$$


<strong>*Sustitución Regresiva*</strong> del sistema triangular superior: se halla primero el valor de $𝑥_5$, con este valor se halla $𝑥_4$, con estos dos valores se halla $𝑥_3$ y así sucesivamente hasta obtener el valor de $𝑥_1$.

$$\begin{matrix} 
x_5 &=& \frac{b_5^{(4)}}{a_{55}^{(4)}}\\
x_4 &=& \frac{b_4^{(3)}-a_{45}^{(3)}x_5}{a_{44}^{(3)}} \\
x_3 &=& \frac{b_3^{(2)}-a_{34}^{(2)}x_4 - a_{35}^{(2)}x_5}{a_{33}^{(2)}} \\
x_2 &=& \frac{b_2^{(1)}-a_{23}^{(1)}x_3 - a_{24}^{(1)}x_4 - a_{25}^{(1)}x_5 }{a_{22}^{(1)}} \\
x_1 &=& \frac{b_1 - a_{12}x_2 - a_{13}x_3 - a_{14}x_4 - a_{15}x_5 }{a_{11}} \\ 
  \end{matrix}$$


De forma general, se puede expresar este procedimiento matemáticamente así:

$$x_i=\frac{b_i-\sum_{j=i+1}^{n}a_{ij}x_j}{a_{ii}} \hspace{1 cm}(i = n, n-1, \ldots, 2,1)$$



### Ejemplo:

Resolver el sistema $4 \times 4$:

$$6x_1  - 2x_2  + 2x_3 +  4x_4 = 12$$

$$12x_1 - 8x_2  + 6x_3 + 10x_4 = 34$$

$$3x_1  - 13x_2 + 9x_3 + 3x_4  = 27$$

$$-6x_1 + 4x_2  +  x_3 - 18x_4 = -38$$

<strong>*Eliminación*:</strong>

- <strong>*Etapa $1$*:</strong> Convertir en ceros todos los elementos de la columna $1$ debajo del elemento pivote $(a_{11}=6)$, seleccionando un multiplicador para cada fila, de forma adecuada. En este caso:

> $M_{21}=a_{21}/a_{11}=12/6 = 2$

> $M_{31}=a_{31}/a_{11}=3/6 = 1/2$ 

> $M_{41}=a_{41}/a_{11}=-6/6 = -1$ 


y calcular:

> la nueva $2$a fila como: $F_2^{(nueva)}=F_{2}− M_{21} F_1 = F_{2}− 2 F_1$. 

> la nueva $3$a fila como: $F_3^{(nueva)}=F_{3}− M_{31} F_1 = F_{3}− F_1/2$. 

> la nueva $4$a fila como: $F_4^{(nueva)}=F_{4}- M_{41} F_1 = F_{4}- (-1)F_1 = F_{4} + F_1$. 


$$\begin{matrix} 
6x_1 &-&  2x_2 &+& 2x_3 &+&  4x_4 &=& 12 \\ 
  0  &-&  4x_2 &+& 2x_3 &+&  2x_4 &=& 10 \\
  0  &-& 12x_2 &+& 8x_3 &+&   x_4 &=& 21 \\
  0  & &  2x_2 &+& 3x_3 &-& 14x_4 &=& -26\\
  \end{matrix}$$


- <strong>*Etapa $2$*:</strong> Convertir en ceros todos los elementos de la columna $2$ debajo del elemento pivote $(a_{22}=-4)$, seleccionando un multiplicador para cada fila, de forma adecuada. En este caso:

> $M_{32}=a_{32}/a_{22}=-12/-4 = 3$ 

> $M_{42}=a_{42}/a_{22}= 2/-4 = -1/2$ 

y calcular 

> la nueva $3$a fila como: $F_3^{(nueva)}=F_{3}−3 F_2$. 

> la nueva $4$a fila como: $F_4^{(nueva)}=F_{4}+ F_2/2$. 


$$\begin{matrix} 
6x_1 &-&  2x_2 &+& 2x_3 &+&  4x_4 &=& 12 \\ 
  0  &-&  4x_2 &+& 2x_3 &+&  2x_4 &=& 10 \\
  0  & &    0  & & 2x_3 &-&  5x_4 &=& -9 \\
  0  & &    0  & & 4x_3 &-& 13x_4 &=& -21\\
  \end{matrix}$$

- <strong>*Etapa $3$*:</strong> Convertir en ceros todos los elementos de la columna $3$ debajo del elemento pivote $(a_{33}=2)$, seleccionando un multiplicador de forma adecuada. En este caso:

> $M_{43}=a_{43}/a_{33}=4/2 = 2$ 

y calcular la nueva $4$a fila como: $F_4^{(nueva)}=F_{4}−2 F_3$. 

$$\begin{matrix} 
6x_1 &-&  2x_2 &+& 2x_3 &+&  4x_4 &=& 12 \\ 
  0  &-&  4x_2 &+& 2x_3 &+&  2x_4 &=& 10 \\
  0  & &    0  & & 2x_3 &-&  5x_4 &=& -9 \\
  0  & &    0  & &  0   &-&  3x_4 &=& -3 \\
  \end{matrix}$$

Se observa que el sistema resultante es triangular superior.

Por último, aplicando el algoritmo de la *sustitución regresiva*:

$$\begin{matrix} 
x_4 &=& \frac{-3}{3}= 1\\
x_3 &=& \frac{-9+5 \times 1}{2} = -2 \\
x_2 &=& \frac{10-2(2)-2(1)}{-4} = -3\\
x_1 &=& \frac{12+2(-3)-2(-2)-4(1)}{6}=1\\
\end{matrix}$$


Vamos a resolver el problema usando programación en el lenguaje Python

In [1]:
import numpy as np
import matplotlib.pyplot as plt

usando los algoritmos vistos:

Lea 𝑨,𝒃

𝑼,𝑩←𝐸𝑙𝑖𝑚𝑖𝑛𝑎𝑐𝑖ó𝑛(𝑨,𝒃)

𝒙←𝐷𝑒𝑠𝑝𝑒𝑗𝑒(𝑼,𝑩)

Imprima 𝒙

Generando la matriz de coeficientes A:

In [2]:
A = np.array([[ 6., - 2, 2,   4],
              [12, - 8, 6,  10],
              [ 3, -13, 9,   3],
              [-6,   4, 1, -18]])
#print(A)

In [3]:
b = np.array([12., 34, 27, -38])
#print(b)

#### Creando la matriza aumentada [A|b]

In [4]:
Ab = np.c_[A,b]
#Ab
#np.shape(Ab)

#### Proceso de *eliminación*

In [5]:
n = A.shape[1]

for k in range(0,n-1):
    print("\n\nEtapa", k+1, "Eliminación columna: ", k+1, "\n")
    for i in range(k+1, n):
        multiplicador = Ab[i][k]/Ab[k][k]
        for j in range(k, n+1):
            Ab[i][j] = Ab[i][j] - multiplicador * Ab[k][j]
        print("\n",Ab)



Etapa 1 Eliminación columna:  1 


 [[  6.  -2.   2.   4.  12.]
 [  0.  -4.   2.   2.  10.]
 [  3. -13.   9.   3.  27.]
 [ -6.   4.   1. -18. -38.]]

 [[  6.  -2.   2.   4.  12.]
 [  0.  -4.   2.   2.  10.]
 [  0. -12.   8.   1.  21.]
 [ -6.   4.   1. -18. -38.]]

 [[  6.  -2.   2.   4.  12.]
 [  0.  -4.   2.   2.  10.]
 [  0. -12.   8.   1.  21.]
 [  0.   2.   3. -14. -26.]]


Etapa 2 Eliminación columna:  2 


 [[  6.  -2.   2.   4.  12.]
 [  0.  -4.   2.   2.  10.]
 [  0.   0.   2.  -5.  -9.]
 [  0.   2.   3. -14. -26.]]

 [[  6.  -2.   2.   4.  12.]
 [  0.  -4.   2.   2.  10.]
 [  0.   0.   2.  -5.  -9.]
 [  0.   0.   4. -13. -21.]]


Etapa 3 Eliminación columna:  3 


 [[  6.  -2.   2.   4.  12.]
 [  0.  -4.   2.   2.  10.]
 [  0.   0.   2.  -5.  -9.]
 [  0.   0.   0.  -3.  -3.]]


In [ ]:
print(Ab)
print(n)
print(k)

for l in range(0,n-1):
    print("\n\nEtapa", l+k+1, "Eliminación columna: ", l+n, "\n")
    for i in range(n):
        multiplicador = Ab[i][n-1]/Ab[n-1][n-1]
        print(multiplicador)
        for j in range(n,0,-1):
            Ab[i][j] = Ab[i][j] - multiplicador * Ab[l][j]
        print("\n",Ab)

#### Proceso de Sustitución regresiva:

In [6]:
x = np.zeros(n)
x[n-1] = Ab[n-1][n] / Ab[n-1][n-1]
for i in range(n-2,-1,-1):
    suma = 0
    for j in range(i+1, n):
        suma = suma + Ab[i][j] * x[j]
    x[i] = (Ab[i][n] - suma) / Ab[i][i]

print(x)

[ 1. -3. -2.  1.]


Resolviendo el SEL por el método que incorpora python por defecto:

In [7]:
x = np.linalg.solve(A,b)
print(x)

[ 1. -3. -2.  1.]


Comprobando que la solución es correcta:

$$\begin{bmatrix} A \end{bmatrix} \begin{Bmatrix} x \end{Bmatrix}  = \begin{Bmatrix} b \end{Bmatrix}$$

In [8]:
A.dot(x) == b

array([ True,  True, False,  True], dtype=bool)

In [9]:
print(A.dot(x))

[ 12.  34.  27. -38.]


In [10]:
print(b)

[ 12.  34.  27. -38.]


## Método de Gauss - Jordan

El método de *Gauss - Jordan* consiste básicamente en continuar con el proceso de eliminación hasta obtener una matriz diagonal (únicamente tiene elementos diferentes de cero en la diagonal principal)

$$\begin{matrix} 
a_{11}^{(7)}x_1 & &    0       & &   0       & &  0         &=& b_{1}^{(7)}  \\ 
  0       & &  a_{22}^{(6)}x_2 & &   0       & &  0         &=& b_{2}^{(6)} \\
  0       & &    0       & & a_{33}^{(5)}x_3 & &  0         &=& b_{3}^{(5)} \\
  0       & &    0       & &   0       & &  a_{44}^{(4)}x_4 &=& b_{4}^{(4)} \\
  \end{matrix}$$

La solución del sistema es "inmediata":

$$\begin{matrix} 
x_1 &=& \frac{b_{1}^{(7)}}{a_{11}^{(7)}}  \\ 
x_2 &=& \frac{b_{2}^{(7)}}{a_{22}^{(6)}}  \\ 
x_3 &=& \frac{b_{3}^{(7)}}{a_{33}^{(5)}}  \\ 
x_4 &=& \frac{b_{4}^{(7)}}{a_{44}^{(4)}}  \\ 
\end{matrix}$$

Continuando con el ejemplo anterior:

$$\begin{matrix} 
6x_1 &-&  2x_2 &+& 2x_3 &+&  4x_4 &=& 12 \\ 
  0  &-&  4x_2 &+& 2x_3 &+&  2x_4 &=& 10 \\
  0  & &    0  & & 2x_3 &-&  5x_4 &=& -9 \\
  0  & &    0  & &  0   &-&  3x_4 &=& -3 \\
  \end{matrix}$$

Se emplea el mismo algoritmo que se venía utilizando, pero ahora se empezará desde la columna $4$, fila $1$, y se eliminan todos los elementos hasta el elemento que está encima del elemento pivote. Una vez eliminados todos los elementos encima del pivote, se continua con la columna $3$ y así sucesivamente hasta la columna $2$.

- <strong>*Etapa $4$*:</strong> Convertir en ceros todos los elementos de la columna $4$ encima del elemento pivote $(a_{44}=-3)$, seleccionando un multiplicador para cada fila, de forma adecuada. En este caso:

> $M_{14} = a_{14}/a_{44} =  4/(-3)$

> $M_{24} = a_{24}/a_{44} =  2/(-3)$ 

> $M_{34} = a_{34}/a_{44} = -5/(-3)$ 


y calcular:

> la nueva $1$a fila como: $F_1^{(nueva)}=F_{1}− M_{14} F_4 = F_{1} + 4/3 F_4$. 

> la nueva $2$a fila como: $F_2^{(nueva)}=F_{2}− M_{24} F_4 = F_{2} + 2/3 F_4$. 

> la nueva $3$a fila como: $F_3^{(nueva)}=F_{3}- M_{34} F_4 = F_{3} - 5/3 F_4 $. 

$$\begin{matrix} 
6x_1 &-&  2x_2 &+& 2x_3 & &     0 &=&  8 \\ 
  0  &-&  4x_2 &+& 2x_3 & &     0 &=&  8 \\
  0  & &    0  & & 2x_3 & &     0 &=& -4 \\
  0  & &    0  & &  0   &-&  3x_4 &=& -3 \\
  \end{matrix}$$

- <strong>*Etapa $5$*:</strong> Convertir en ceros todos los elementos de la columna $3$ encima del elemento pivote $(a_{33}=2)$, seleccionando un multiplicador para cada fila, de forma adecuada. En este caso:

> $M_{13} = a_{13}/a_{33} = 2/2 = 1$ 

> $M_{23} = a_{23}/a_{33} = 2/2 = 1$ 

y calcular 

> la nueva $1$a fila como: $F_1^{(nueva)} = F_{1} − F_3$. 

> la nueva $2$a fila como: $F_2^{(nueva)} = F_{2} - F_3$. 


$$\begin{matrix} 
6x_1 &-&  2x_2 & & 0    & &     0 &=&  12 \\ 
  0  &-&  4x_2 & & 0    & &     0 &=&  12 \\
  0  & &    0  & & 2x_3 & &     0 &=& -4 \\
  0  & &    0  & &  0   &-&  3x_4 &=& -3 \\
  \end{matrix}$$

- <strong>*Etapa $6$*:</strong> Convertir en ceros todos los elementos de la columna $2$ encima del elemento pivote $(a_{22}=-4)$, seleccionando un multiplicador de forma adecuada. En este caso:

> $M_{12} = a_{12}/a_{22} = -2/-4 = 1/2$ 

y calcular la nueva $1$a fila como: $F_1^{(nueva)}=F_{1}− F_2/2$. 

$$\begin{matrix} 
6x_1 & &     0 & & 0    & &     0 &=&  6 \\ 
  0  &-&  4x_2 & & 0    & &     0 &=&  12 \\
  0  & &    0  & & 2x_3 & &     0 &=& -4 \\
  0  & &    0  & &  0   &-&  3x_4 &=& -3 \\
  \end{matrix}$$

La solución es inmediata:

$$\begin{matrix} 
x_1 &=& \frac{6}{6} &=& 1 \\ 
x_2 &=& \frac{12}{-4} &=& -3  \\ 
x_3 &=& \frac{-4}{-2} &=& -2  \\ 
x_4 &=& \frac{-3}{-3} &=& 1  \\ 
\end{matrix}$$

Continuando con el programa:

In [ ]:
print(Ab)